# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1brFSTV0JSiE3QhrCTJXeC-I5bWkKWKoD

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

a=s.split(" ")
print(a)

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742
print("The diameter of {0} is {1} kilometers.".format(planet,diameter))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])



"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

n=10
a=[]
b=[]
for i in range(0,n):
  a.append(0)
  b.append(5)



"""## 5. Create an array of all the even integers from 20 to 35"""

a=[]
i=20
while(i<=35):
  if(i%2==0):
    a.append(i)
  i=i+1

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

r=3
c=3
a=[]
l=0
for i in range(0,r):
  b=[]
  for j in range(0,c):
    b.append(l)
    l=l+1
  a.append(b)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

c=a+b

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd
data = [['A', 10], ['B', 15], ['C', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
print(df)



"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import pandas as pd 
pd.date_range('2023-01-01', '2023-02-10')

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""



import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
a=pd.DataFrame(lists,columns=["","",""])
print(a)